name: CI

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Bakgrunnur.xm'
      - 'control'
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Theos Setup Action
        uses: axs66/theos-action@main

      # ✅ 拉取 Preferences.framework 的必要部分
      - name: Clone Preferences.framework (sparse)
        run: |
          git clone --depth=1 --filter=blob:none --sparse https://github.com/axs66/Preferences.framework.git $GITHUB_WORKSPACE/Preferences.framework
          cd $GITHUB_WORKSPACE/Preferences.framework
          git sparse-checkout set Headers Preferences
          # 确保 Theos 的 lib 路径存在
          mkdir -p $THEOS/lib
          # 拷贝框架到 Theos 可识别位置
          cp -R $GITHUB_WORKSPACE/Preferences.framework $THEOS/lib/Preferences.framework

      - name: Clean previous packages
        run: rm -f ${{ github.workspace }}/packages/*.deb

      - name: Build DEB (rootless + roothide)
        run: |
          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: List generated DEBs
        run: ls -lh ${{ github.workspace }}/packages

      - name: Create GitHub Release
        run: |
          VERSION=$(date +v%Y%m%d%H%M)
          gh release create $VERSION ${{ github.workspace }}/packages/*.deb --title "bakgrunnur $VERSION" --notes "自动构建 .deb 安装包"
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      - name: Upload DEB to workflow artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: bakgrunnur
          path: ${{ github.workspace }}/packages/*.deb
